/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-04-15 03:41:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.post;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kh.post.model.vo.Post;
import com.kh.common.model.vo.PageInfo;
import com.kh.common.model.vo.Attachment;
import com.kh.member.model.vo.Member;

public final class reviewPostListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/post/../common/menubar.jsp", Long.valueOf(1681527264440L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.common.model.vo.PageInfo");
    _jspx_imports_classes.add("com.kh.post.model.vo.Post");
    _jspx_imports_classes.add("com.kh.common.model.vo.Attachment");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Post> list = (ArrayList<Post>)request.getAttribute("list");
  ArrayList<Attachment> flist = (ArrayList<Attachment>)request.getAttribute("flist");
	PageInfo pi = (PageInfo)request.getAttribute("pi");
  int listsize = list.size();
	System.out.println("listsize : " + listsize);

	int currentPage = pi.getCurrentPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();
	int maxPage = pi.getMaxPage();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"english\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>exported project</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta property=\"twitter:card\" content=\"summary_large_image\" />\r\n");
      out.write("\r\n");
      out.write("    <style data-tag=\"reset-style-sheet\">\r\n");
      out.write("      html {\r\n");
      out.write("        line-height: 1.15;\r\n");
      out.write("      }\r\n");
      out.write("      body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("      }\r\n");
      out.write("      * {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        border-width: 0;\r\n");
      out.write("        border-style: solid;\r\n");
      out.write("      }\r\n");
      out.write("      p,\r\n");
      out.write("      li,\r\n");
      out.write("      ul,\r\n");
      out.write("      pre,\r\n");
      out.write("      div,\r\n");
      out.write("      h1,\r\n");
      out.write("      h2,\r\n");
      out.write("      h3,\r\n");
      out.write("      h4,\r\n");
      out.write("      h5,\r\n");
      out.write("      h6,\r\n");
      out.write("      figure,\r\n");
      out.write("      blockquote,\r\n");
      out.write("      figcaption {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("      }\r\n");
      out.write("      button {\r\n");
      out.write("        background-color: transparent;\r\n");
      out.write("      }\r\n");
      out.write("      button,\r\n");
      out.write("      input,\r\n");
      out.write("      optgroup,\r\n");
      out.write("      select,\r\n");
      out.write("      textarea {\r\n");
      out.write("        font-family: inherit;\r\n");
      out.write("        font-size: 100%;\r\n");
      out.write("        line-height: 1.15;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("      }\r\n");
      out.write("      button,\r\n");
      out.write("      select {\r\n");
      out.write("        text-transform: none;\r\n");
      out.write("      }\r\n");
      out.write("      button,\r\n");
      out.write("      [type=\"button\"],\r\n");
      out.write("      [type=\"reset\"],\r\n");
      out.write("      [type=\"submit\"] {\r\n");
      out.write("        -webkit-appearance: button;\r\n");
      out.write("      }\r\n");
      out.write("      button::-moz-focus-inner,\r\n");
      out.write("      [type=\"button\"]::-moz-focus-inner,\r\n");
      out.write("      [type=\"reset\"]::-moz-focus-inner,\r\n");
      out.write("      [type=\"submit\"]::-moz-focus-inner {\r\n");
      out.write("        border-style: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("      }\r\n");
      out.write("      button:-moz-focus,\r\n");
      out.write("      [type=\"button\"]:-moz-focus,\r\n");
      out.write("      [type=\"reset\"]:-moz-focus,\r\n");
      out.write("      [type=\"submit\"]:-moz-focus {\r\n");
      out.write("        outline: 1px dotted ButtonText;\r\n");
      out.write("      }\r\n");
      out.write("      a {\r\n");
      out.write("        color: inherit;\r\n");
      out.write("        text-decoration: inherit;\r\n");
      out.write("      }\r\n");
      out.write("      input {\r\n");
      out.write("        padding: 2px 4px;\r\n");
      out.write("      }\r\n");
      out.write("      img {\r\n");
      out.write("        display: block;\r\n");
      out.write("      }\r\n");
      out.write("      html {\r\n");
      out.write("        scroll-behavior: smooth;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- CSS only -->\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("    <style data-tag=\"default-style-sheet\">\r\n");
      out.write("      html {\r\n");
      out.write("        font-family: Inter;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      body {\r\n");
      out.write("        font-weight: 400;\r\n");
      out.write("        font-style: normal;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        text-transform: none;\r\n");
      out.write("        letter-spacing: normal;\r\n");
      out.write("        line-height: 1.15;\r\n");
      out.write("        color: var(--dl-color-gray-black);\r\n");
      out.write("        background-color: var(--dl-color-gray-white);\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap\"\r\n");
      out.write("      data-tag=\"font\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap\"\r\n");
      out.write("      data-tag=\"font\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/style_reviewlist.css\" />\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');

	
	String contextPath = request.getContextPath(); // "/jsp"
	
	Member loginUser = (Member)session.getAttribute("loginUser"); // 로그인한 유저의 정보
	
	String alertMsg = (String)session.getAttribute("alertMsg"); // alert 메세지
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"english\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>exported project</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta property=\"twitter:card\" content=\"summary_large_image\" />\r\n");
      out.write("<!-- CSS only -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\"\r\n");
      out.write("	crossorigin=\"anonymous\" />\r\n");
      out.write("<style data-tag=\"reset-style-sheet\">\r\n");
      out.write("html {\r\n");
      out.write("	line-height: 1.15;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	border-width: 0;\r\n");
      out.write("	border-style: solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p, li, ul, pre, div, h1, h2, h3, h4, h5, h6, figure, blockquote,\r\n");
      out.write("	figcaption {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	background-color: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button, input, optgroup, select, textarea {\r\n");
      out.write("	font-family: inherit;\r\n");
      out.write("	font-size: 100%;\r\n");
      out.write("	line-height: 1.15;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button, select {\r\n");
      out.write("	text-transform: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button, [type=\"button\"], [type=\"reset\"], [type=\"submit\"] {\r\n");
      out.write("	-webkit-appearance: button;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button::-moz-focus-inner, [type=\"button\"]::-moz-focus-inner, [type=\"reset\"]::-moz-focus-inner,\r\n");
      out.write("	[type=\"submit\"]::-moz-focus-inner {\r\n");
      out.write("	border-style: none;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:-moz-focus, [type=\"button\"]:-moz-focus, [type=\"reset\"]:-moz-focus,\r\n");
      out.write("	[type=\"submit\"]:-moz-focus {\r\n");
      out.write("	outline: 1px dotted ButtonText;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	color: inherit;\r\n");
      out.write("	text-decoration: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	padding: 2px 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("	scroll-behavior: smooth;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<style data-tag=\"default-style-sheet\">\r\n");
      out.write("html {\r\n");
      out.write("	font-family: Inter;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	text-transform: none;\r\n");
      out.write("	letter-spacing: normal;\r\n");
      out.write("	line-height: 1.15;\r\n");
      out.write("	color: var(- -dl-color-gray-black);\r\n");
      out.write("	background-color: var(- -dl-color-gray-white);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-box1 {\r\n");
      out.write("	background-color: #f9f9f9;\r\n");
      out.write("	min-width: 160px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	border: 1px solid #f9f9f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("/* navigator 에 대한 작업용 임시스타일 */\r\n");
      out.write("#navigator {\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 전체를 감사는 navi */\r\n");
      out.write("#navi {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	/*\r\n");
      out.write("            p 태그와 마찬가지로 ul 태그 또한 위, 아래로 기본 margin 이 잡혀있음\r\n");
      out.write("            또한 ul 태그는 padding이 왼쪽에 기본적으로 존재함\r\n");
      out.write("            => margin : 0px; 과 padding : 0px; 으로 margin과 padding을 없애기\r\n");
      out.write("        */\r\n");
      out.write("	margin: 0px;\r\n");
      out.write("	padding: 0px; /* padding 값 조정으로 메뉴 가운데 배치 가능 */\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 메인 메뉴 나타내는 li 태그들 */\r\n");
      out.write("#navi>li {\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 15%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 메뉴 문구를 나타내는 a 태그들 */\r\n");
      out.write("#navi a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: lightcoral;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	font-weight: 900;\r\n");
      out.write("	/*\r\n");
      out.write("                a 태그는 인라인요소이기 때문에\r\n");
      out.write("                width, height 속성이 적용되지 않음\r\n");
      out.write("                => display : block;으로 블럭요소화 시켜줄것임\r\n");
      out.write("            */\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	/*vertical-align : middle;*/ /* verical-align 은 블럭요소에서 적용되지 않음 */\r\n");
      out.write("	line-height: 35px;\r\n");
      out.write("	/*\r\n");
      out.write("                line_height 속성은 블럭요소에 대한 장편조절 속성\r\n");
      out.write("                보통은 블럭요소의 세로길이만큼 주면 알아서 가운데로 옴\r\n");
      out.write("            */\r\n");
      out.write("}\r\n");
      out.write("/* 메뉴에 마우스가 올라갔을 때 추가적인 속성 */\r\n");
      out.write("#navi a:hover {\r\n");
      out.write("	color: crimson;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 서브메뉴에 해당되는 ul에 대한 스타일 */\r\n");
      out.write("#navi>li>ul {\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	padding: 0px;\r\n");
      out.write("	display: none; /* 평소에는 안보여지게끔 숨김 처리 */\r\n");
      out.write("}\r\n");
      out.write("/* 메인 메뉴에 마우스가 올라가는 순간 서브메뉴가 보여지게끔 스타일 부여*/\r\n");
      out.write("#navi>li:hover>ul {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 혹시 몰라서 서브메뉴 자체에도 효과 부여 */\r\n");
      out.write("#navi>li>ul:hover {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 추가적으로 글씨 크기조정, 스타일, ... */\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap\"\r\n");
      out.write("	data-tag=\"font\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap\"\r\n");
      out.write("	data-tag=\"font\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./style.css\" />\r\n");
      out.write("<link href=\"resources/css/navbar11.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div>\r\n");
      out.write("		<div class=\"navbar11-navbar1\">\r\n");
      out.write("			<div class=\"navbar11-container1\">\r\n");
      out.write("				<img onclick=\"location.href='");
      out.print( contextPath );
      out.write("'\" style=\"cursor: pointer\"\r\n");
      out.write("					src=\"resources/css/logoimg+logoname.png\" alt=\"logoI204\"\r\n");
      out.write("					class=\"navbar11-logo\" />\r\n");
      out.write("				<div class=\"navbar11-column1\">\r\n");
      out.write("					<div class=\"navbar11-column2\">\r\n");
      out.write("						<span onclick=\"location.href='#1'\"\r\n");
      out.write("							class=\"navbar11-text TextRegularNormal\" style=\"cursor: pointer\">\r\n");
      out.write("							<div class=\"dropdown\">\r\n");
      out.write("								<button class=\"btn btn-secondary dropdown-toggle\"\r\n");
      out.write("									style=\"background-color: rgba(64, 81, 59, 1); border: 0px; border-radius: 0px;\"\r\n");
      out.write("									type=\"button\" id=\"dropdownMenuButton1\"\r\n");
      out.write("									data-bs-toggle=\"dropdown\" aria-expanded=\"false\">게시판</button>\r\n");
      out.write("								<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("									<li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/plist.bo?currentPage=1\">자유 게시판</a></li>\r\n");
      out.write("									<li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/review.bo?currentPage=1\">사진 게시판</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"dropdown\">\r\n");
      out.write("							<button class=\"btn btn-secondary\"\r\n");
      out.write("								onclick=\"location.href='");
      out.print( contextPath );
      out.write("/menu.mn'\"\r\n");
      out.write("								style=\"background-color: rgba(64, 81, 59, 1); border: 0px; border-radius: 0px;\"\r\n");
      out.write("								type=\"button\" id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("								aria-expanded=\"false\">메뉴 정보</button>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dropdown\">\r\n");
      out.write("							<button class=\"btn btn-secondary\"\r\n");
      out.write("								style=\"background-color: rgba(64, 81, 59, 1); border: 0px; border-radius: 0px;\"\r\n");
      out.write("								type=\"button\" id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("								aria-expanded=\"false\">매장 정보</button>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"dropdown\">\r\n");
      out.write("							<button class=\"btn btn-secondary dropdown-toggle\"\r\n");
      out.write("								style=\"background-color: rgba(64, 81, 59, 1); border: 0px; border-radius: 0px;\"\r\n");
      out.write("								type=\"button\" id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("								aria-expanded=\"false\">더보기</button>\r\n");
      out.write("							<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/myPage.me\">마이 페이지</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">문의 하기</a></li>\r\n");
      out.write("\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					");
 if(loginUser == null) { // 로그인 하기 전  
      out.write("\r\n");
      out.write("						<div class=\"navbar11-column3\">\r\n");
      out.write("							<button onclick=\"location.href='");
      out.print( contextPath );
      out.write("/loginPage.me'\"\r\n");
      out.write("								class=\"navbar11-button\" style=\"cursor: pointer\">\r\n");
      out.write("								<span class=\"navbar11-text08 TextRegularNormal\"> <span>로그인</span>\r\n");
      out.write("								</span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					");
 } else { // 로그인 한 후 
      out.write("\r\n");
      out.write("						<div class=\"navbar11-column3\">\r\n");
      out.write("							<button onclick=\"location.href='");
      out.print( contextPath );
      out.write("/logout.me'\"\r\n");
      out.write("								class=\"navbar11-button\" style=\"cursor: pointer\">\r\n");
      out.write("								<span class=\"navbar11-text08 TextRegularNormal\"> <span>로그아웃</span>\r\n");
      out.write("								</span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("    <div class=\".container\">\r\n");
      out.write("      <link href=\"resources/css/blog6.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("      <div class=\"blog6-container\">\r\n");
      out.write("        <div class=\"blog6-blog6\" style=\"width: \">\r\n");
      out.write("          <div class=\"blog6-section-title\">\r\n");
      out.write("            <div class=\"blog6-content\" style=\"margin: auto\">\r\n");
      out.write("              <span class=\"blog6-text02 HeadingH1\" ST>\r\n");
      out.write("                <span>리뷰 게시판</span>\r\n");
      out.write("              </span>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"blog6-content01\">\r\n");
      out.write("            <div class=\"blog6-card\" style=\"width: 1312px; margin: 0 auto;\">\r\n");
      out.write("              <img\r\n");
      out.write("                src=\"resources/css/public/playground_assets/placeholderimagei308-xjo-500h.png\"\r\n");
      out.write("                alt=\"PlaceholderImageI308\"\r\n");
      out.write("                class=\"blog6-placeholder-image\"\r\n");
      out.write("              />\r\n");
      out.write("              <div class=\"blog6-content02\">\r\n");
      out.write("                <div class=\"blog6-content03\">\r\n");
      out.write("                  <div class=\"blog6-info\">\r\n");
      out.write("                    <div class=\"blog6-frame61\">\r\n");
      out.write("                      <span class=\"blog6-text06 TextSmallSemiBold\">\r\n");
      out.write("                        <span>Category</span>\r\n");
      out.write("                      </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <span class=\"blog6-text08 TextSmallSemiBold\">\r\n");
      out.write("                      <span>5 min read</span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"blog6-title\">\r\n");
      out.write("                    <span class=\"blog6-text10 HeadingH4\">\r\n");
      out.write("                      <span>오늘의 베스트 리뷰 제목</span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"blog6-text12 TextRegularNormal\">\r\n");
      out.write("                      <span>\r\n");
      out.write("                        내용 내용 내용 내용 내용 내용\r\n");
      out.write("                      </span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"blog6-button\">\r\n");
      out.write("                  <span class=\"blog6-text14 TextRegularNormal\">\r\n");
      out.write("                    <span onclick=\"location.href='");
      out.print( contextPath );
      out.write("/rdetail.bo'\">상세 보기</span>\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <img\r\n");
      out.write("                    src=\"resources/css/public/playground_assets/iconchevronrighti308-w0e.svg\"\r\n");
      out.write("                    alt=\"IconChevronRightI308\"\r\n");
      out.write("                    class=\"blog6-icon-chevron-right\"\r\n");
      out.write("                  />\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br><br><br><br><br><br><br>\r\n");
      out.write("            <!-- 카테고리 -->\r\n");
      out.write("            <!-- <div class=\"blog6-content04\">\r\n");
      out.write("              <div class=\"blog6-categories\">\r\n");
      out.write("                <button class=\"blog6-button01\">\r\n");
      out.write("                  <span class=\"blog6-text16 TextRegularNormal\">\r\n");
      out.write("                    <span>View all</span>\r\n");
      out.write("                  </span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"blog6-button02\">\r\n");
      out.write("                  <span class=\"blog6-text18 TextRegularNormal\">\r\n");
      out.write("                    <span>Category one</span>\r\n");
      out.write("                  </span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"blog6-button03\">\r\n");
      out.write("                  <span class=\"blog6-text20 TextRegularNormal\">\r\n");
      out.write("                    <span>Category two</span>\r\n");
      out.write("                  </span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"blog6-button04\">\r\n");
      out.write("                  <span class=\"blog6-text22 TextRegularNormal\">\r\n");
      out.write("                    <span>Category three</span>\r\n");
      out.write("                  </span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"blog6-button05\">\r\n");
      out.write("                  <span class=\"blog6-text24 TextRegularNormal\">\r\n");
      out.write("                    <span>Category four</span>\r\n");
      out.write("                  </span>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div> -->\r\n");
      out.write("              <!-- --------------------------- 몸통 ---------------------------------------------- -->\r\n");
      out.write("              <div class=\"blog6-content05\">\r\n");
      out.write("                <div class=\"blog6-row\">\r\n");
      out.write("                  ");
 if(listsize >= 1 ) {
      out.write("\r\n");
      out.write("                  <div class=\"blog6-card1\">\r\n");
      out.write("                    ");
 if(flist.get(0) == null) { 
      out.write("\r\n");
      out.write("                      <img src=\"resources/img/1.png\" width=\"416\" height=\"300\"\r\n");
      out.write("                        style=\"margin-bottom: 30px;\">\r\n");
      out.write("                      ");
 } else {
      out.write("\r\n");
      out.write("                      <img src=\"");
      out.print( contextPath );
      out.write('/');
      out.print( flist.get(0).getFilePath() + flist.get(0).getChangeName() );
      out.write("\"\r\n");
      out.write("                      width=\"416\" height=\"300\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("                      ");
 } 
      out.write("\r\n");
      out.write("                    <div class=\"blog6-content06\">\r\n");
      out.write("                      <div class=\"blog6-info1\">\r\n");
      out.write("                        <div class=\"blog6-frame611\">\r\n");
      out.write("                          <span class=\"blog6-text26 TextSmallSemiBold\">\r\n");
      out.write("                            <span>");
      out.print( list.get(0).getMemberNickname() );
      out.write("</span>\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"blog6-text28 TextSmallSemiBold\">\r\n");
      out.write("                          <span>");
      out.print( list.get(0).getPostDate() );
      out.write("</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"blog6-title1\">\r\n");
      out.write("                        <span class=\"blog6-text30 HeadingH5\">\r\n");
      out.write("                          <span>");
      out.print( list.get(0).getPostTitle() );
      out.write("</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"blog6-text32 TextRegularNormal\">\r\n");
      out.write("                          <span>\r\n");
      out.write("                            ");
      out.print( list.get(0).getPostContent() );
      out.write("\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"blog6-button06\">\r\n");
      out.write("                      <span class=\"blog6-text34 TextRegularNormal\">\r\n");
      out.write("                        <span onclick=\"location.href='");
      out.print( contextPath );
      out.write("/rdetail.bo?pno=");
      out.print( list.get(0).getPostNo() );
      out.write("'\">자세히 보기</span>\r\n");
      out.write("                      </span>\r\n");
      out.write("                      <img\r\n");
      out.write("                        src=\"resources/css/public/playground_assets/iconchevronrighti308-vlfs.svg\"\r\n");
      out.write("                        alt=\"IconChevronRightI308\"\r\n");
      out.write("                        class=\"blog6-icon-chevron-right1\"\r\n");
      out.write("                      />\r\n");
      out.write("                    </button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  ");
 if(listsize >= 2 ) {
      out.write("\r\n");
      out.write("                  <div class=\"blog6-card2\">\r\n");
      out.write("                    ");
 if(flist.get(1) == null) { 
      out.write("\r\n");
      out.write("                      <img src=\"resources/img/1.png\" width=\"416\" height=\"300\"\r\n");
      out.write("                        style=\"margin-bottom: 30px;\">\r\n");
      out.write("                      ");
 } else {
      out.write("\r\n");
      out.write("                      <img src=\"");
      out.print( contextPath );
      out.write('/');
      out.print( flist.get(1).getFilePath() + flist.get(1).getChangeName() );
      out.write("\"\r\n");
      out.write("                      width=\"416\" height=\"300\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("                      ");
 } 
      out.write("\r\n");
      out.write("                    <div class=\"blog6-content07\">\r\n");
      out.write("                      <div class=\"blog6-info2\">\r\n");
      out.write("                        <div class=\"blog6-frame612\">\r\n");
      out.write("                          <span class=\"blog6-text36 TextSmallSemiBold\">\r\n");
      out.write("                            <span>");
      out.print( list.get(1).getMemberNickname() );
      out.write("</span>\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"blog6-text38 TextSmallSemiBold\">\r\n");
      out.write("                          <span>");
      out.print( list.get(1).getPostDate() );
      out.write("</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"blog6-title2\">\r\n");
      out.write("                        <span class=\"blog6-text40 HeadingH5\">\r\n");
      out.write("                          <span>");
      out.print( list.get(1).getPostTitle() );
      out.write("</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"blog6-text42 TextRegularNormal\">\r\n");
      out.write("                          <span>\r\n");
      out.write("                            ");
      out.print( list.get(1).getPostContent() );
      out.write("\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"blog6-button07\">\r\n");
      out.write("                      <span class=\"blog6-text44 TextRegularNormal\">\r\n");
      out.write("                        <span onclick=\"location.href='");
      out.print( contextPath );
      out.write("/rdetail.bo?pno=");
      out.print( list.get(1).getPostNo() );
      out.write("'\">자세히 보기</span>\r\n");
      out.write("                      </span>\r\n");
      out.write("                      <img\r\n");
      out.write("                        src=\"resources/css/public/playground_assets/iconchevronrighti308-hb4h.svg\"\r\n");
      out.write("                        alt=\"IconChevronRightI308\"\r\n");
      out.write("                        class=\"blog6-icon-chevron-right2\"\r\n");
      out.write("                      />\r\n");
      out.write("                    </button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  ");
 if(listsize >= 3 ) {
      out.write("\r\n");
      out.write("                  <div class=\"blog6-card3\">\r\n");
      out.write("                    ");
 if(flist.get(2) == null) { 
      out.write("\r\n");
      out.write("                      <img src=\"resources/img/1.png\" width=\"416\" height=\"300\"\r\n");
      out.write("                        style=\"margin-bottom: 30px;\">\r\n");
      out.write("                      ");
 } else {
      out.write("\r\n");
      out.write("                      <img src=\"");
      out.print( contextPath );
      out.write('/');
      out.print( flist.get(2).getFilePath() + flist.get(2).getChangeName() );
      out.write("\"\r\n");
      out.write("                      width=\"416\" height=\"300\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("                      ");
 } 
      out.write("\r\n");
      out.write("                    <div class=\"blog6-content08\">\r\n");
      out.write("                      <div class=\"blog6-info3\">\r\n");
      out.write("                        <div class=\"blog6-frame613\">\r\n");
      out.write("                          <span class=\"blog6-text46 TextSmallSemiBold\">\r\n");
      out.write("                            <span>");
      out.print( list.get(2).getMemberNickname() );
      out.write("</span>\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"blog6-text48 TextSmallSemiBold\">\r\n");
      out.write("                          <span>");
      out.print( list.get(2).getPostDate() );
      out.write("</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"blog6-title3\">\r\n");
      out.write("                        <span class=\"blog6-text50 HeadingH5\">\r\n");
      out.write("                          <span>");
      out.print( list.get(2).getPostTitle() );
      out.write("</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"blog6-text52 TextRegularNormal\">\r\n");
      out.write("                          <span>\r\n");
      out.write("                             ");
      out.print( list.get(2).getPostContent() );
      out.write("\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"blog6-button08\">\r\n");
      out.write("                      <span class=\"blog6-text54 TextRegularNormal\">\r\n");
      out.write("                        <span onclick=\"location.href='");
      out.print( contextPath );
      out.write("/rdetail.bo?pno=");
      out.print( list.get(2).getPostNo() );
      out.write("'\">자세히 보기</span>\r\n");
      out.write("                      </span>\r\n");
      out.write("                      <img\r\n");
      out.write("                        src=\"resources/css/public/playground_assets/iconchevronrighti308-mxq.svg\"\r\n");
      out.write("                        alt=\"IconChevronRightI308\"\r\n");
      out.write("                        class=\"blog6-icon-chevron-right3\"\r\n");
      out.write("                      />\r\n");
      out.write("                    </button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <!-- -------------------------------------2열------------------------------------------- -->\r\n");
      out.write("                <div class=\"blog6-row1\">\r\n");
      out.write("                  ");
 if(listsize >= 4 ) {
      out.write("\r\n");
      out.write("                  <div class=\"blog6-card4\">\r\n");
      out.write("                    ");
 if(flist.get(3) == null) { 
      out.write("\r\n");
      out.write("                      <img src=\"resources/img/1.png\" width=\"416\" height=\"300\"\r\n");
      out.write("                        style=\"margin-bottom: 30px;\">\r\n");
      out.write("                      ");
 } else {
      out.write("\r\n");
      out.write("                      <img src=\"");
      out.print( contextPath );
      out.write('/');
      out.print( flist.get(3).getFilePath() + flist.get(3).getChangeName() );
      out.write("\"\r\n");
      out.write("                      width=\"416\" height=\"300\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("                      ");
 } 
      out.write("\r\n");
      out.write("                    <div class=\"blog6-content09\">\r\n");
      out.write("                      <div class=\"blog6-info4\">\r\n");
      out.write("                        <div class=\"blog6-frame614\">\r\n");
      out.write("                          <span class=\"blog6-text56 TextSmallSemiBold\">\r\n");
      out.write("                            <span>");
      out.print( list.get(3).getMemberNickname() );
      out.write("</span>\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"blog6-text58 TextSmallSemiBold\">\r\n");
      out.write("                          <span>");
      out.print( list.get(3).getPostDate() );
      out.write("</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"blog6-title4\">\r\n");
      out.write("                        <span class=\"blog6-text60 HeadingH5\">\r\n");
      out.write("                          <span>");
      out.print( list.get(3).getPostTitle() );
      out.write("</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"blog6-text62 TextRegularNormal\">\r\n");
      out.write("                          <span>\r\n");
      out.write("                             ");
      out.print( list.get(3).getPostContent() );
      out.write("\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"blog6-button09\">\r\n");
      out.write("                      <span class=\"blog6-text64 TextRegularNormal\">\r\n");
      out.write("                        <span onclick=\"location.href='");
      out.print( contextPath );
      out.write("/rdetail.bo?pno=");
      out.print( list.get(3).getPostNo() );
      out.write("'\">자세히 보기</span>\r\n");
      out.write("                      </span>\r\n");
      out.write("                      <img\r\n");
      out.write("                        src=\"resources/css/public/playground_assets/iconchevronrighti308-2dp.svg\"\r\n");
      out.write("                        alt=\"IconChevronRightI308\"\r\n");
      out.write("                        class=\"blog6-icon-chevron-right4\"\r\n");
      out.write("                      />\r\n");
      out.write("                    </button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  ");
 if(listsize >= 5 ) {
      out.write("\r\n");
      out.write("                  <!--  -->\r\n");
      out.write("                  <div class=\"blog6-card5\">\r\n");
      out.write("                    ");
 if(flist.get(4) == null) { 
      out.write("\r\n");
      out.write("                      <img src=\"resources/img/1.png\" width=\"416\" height=\"300\"\r\n");
      out.write("                        style=\"margin-bottom: 30px;\">\r\n");
      out.write("                      ");
 } else {
      out.write("\r\n");
      out.write("                      <img src=\"");
      out.print( contextPath );
      out.write('/');
      out.print( flist.get(4).getFilePath() + flist.get(4).getChangeName() );
      out.write("\"\r\n");
      out.write("                      width=\"416\" height=\"300\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("                      ");
 } 
      out.write("\r\n");
      out.write("                    <div class=\"blog6-content10\">\r\n");
      out.write("                      <div class=\"blog6-info5\">\r\n");
      out.write("                        <div class=\"blog6-frame615\">\r\n");
      out.write("                          <span class=\"blog6-text66 TextSmallSemiBold\">\r\n");
      out.write("                            <span>");
      out.print( list.get(4).getMemberNickname() );
      out.write("</span>\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"blog6-text68 TextSmallSemiBold\">\r\n");
      out.write("                          <span>");
      out.print( list.get(4).getPostDate() );
      out.write("</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"blog6-title5\">\r\n");
      out.write("                        <span class=\"blog6-text70 HeadingH5\">\r\n");
      out.write("                          <span>");
      out.print( list.get(4).getPostTitle() );
      out.write("</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"blog6-text72 TextRegularNormal\">\r\n");
      out.write("                          <span>\r\n");
      out.write("                            ");
      out.print( list.get(4).getPostContent() );
      out.write("\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"blog6-button10\">\r\n");
      out.write("                      <span class=\"blog6-text74 TextRegularNormal\">\r\n");
      out.write("                        <span onclick=\"location.href='");
      out.print( contextPath );
      out.write("/rdetail.bo?pno=");
      out.print( list.get(4).getPostNo() );
      out.write("'\">자세히 보기</span>\r\n");
      out.write("                      </span>\r\n");
      out.write("                      <img\r\n");
      out.write("                        src=\"resources/css/public/playground_assets/iconchevronrighti308-noh.svg\"\r\n");
      out.write("                        alt=\"IconChevronRightI308\"\r\n");
      out.write("                        class=\"blog6-icon-chevron-right5\"\r\n");
      out.write("                      />\r\n");
      out.write("                    </button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  <!--  -->\r\n");
      out.write("                  ");
 if(listsize >= 6 ) {
      out.write("\r\n");
      out.write("                  <div class=\"blog6-card6\">\r\n");
      out.write("                    ");
 if(flist.get(5) == null) { 
      out.write("\r\n");
      out.write("                    <img src=\"resources/img/1.png\" width=\"416\" height=\"300\"\r\n");
      out.write("                      style=\"margin-bottom: 30px;\">\r\n");
      out.write("                    ");
 } else {
      out.write("\r\n");
      out.write("                    <img src=\"");
      out.print( contextPath );
      out.write('/');
      out.print( flist.get(5).getFilePath() + flist.get(5).getChangeName() );
      out.write("\"\r\n");
      out.write("                    width=\"416\" height=\"300\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    <div class=\"blog6-content11\">\r\n");
      out.write("                      <div class=\"blog6-info6\">\r\n");
      out.write("                        <div class=\"blog6-frame616\">\r\n");
      out.write("                          <span class=\"blog6-text76 TextSmallSemiBold\">\r\n");
      out.write("                            <span>");
      out.print( list.get(5).getMemberNickname() );
      out.write("</span>\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"blog6-text78 TextSmallSemiBold\">\r\n");
      out.write("                          <span>");
      out.print( list.get(5).getPostDate() );
      out.write("</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"blog6-title6\">\r\n");
      out.write("                        <span class=\"blog6-text80 HeadingH5\">\r\n");
      out.write("                          <span>");
      out.print( list.get(5).getPostTitle() );
      out.write("</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"blog6-text82 TextRegularNormal\">\r\n");
      out.write("                          <span>\r\n");
      out.write("                            ");
      out.print( list.get(5).getPostContent() );
      out.write("\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"blog6-button11\">\r\n");
      out.write("                      <span class=\"blog6-text84 TextRegularNormal\">\r\n");
      out.write("                        <span onclick=\"location.href='");
      out.print( contextPath );
      out.write("/rdetail.bo?pno=");
      out.print( list.get(5).getPostNo() );
      out.write("'\">자세히 보기</span>\r\n");
      out.write("                      </span>\r\n");
      out.write("                      <img\r\n");
      out.write("                        src=\"resources/css/public/playground_assets/iconchevronrighti308-o54k.svg\"\r\n");
      out.write("                        alt=\"IconChevronRightI308\"\r\n");
      out.write("                        class=\"blog6-icon-chevron-right6\"\r\n");
      out.write("                      />\r\n");
      out.write("                    </button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <!--  -->\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- ---------------------------- 바디 끝 --------------------------------------- -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div align=\"center\" class=\"paging-area\">\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(currentPage != 1){ 
      out.write("\r\n");
      out.write("        <button onclick=\"location.href='");
      out.print( contextPath);
      out.write("/review.bo?currentPage=");
      out.print(currentPage - 1);
      out.write("';\">&lt;</button>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 for(int p = startPage; p <= endPage; p++){ 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("          ");
if(p != currentPage){ 
      out.write("\r\n");
      out.write("            <button onclick=\"location.href='");
      out.print( contextPath );
      out.write("/review.bo?currentPage=");
      out.print(p);
      out.write("';\">");
      out.print( p );
      out.write("</button>\r\n");
      out.write("          ");
} else{ 
      out.write("\r\n");
      out.write("            <!-- 현재 내가 보고있는 페이지일 경우에는 클릭이 안되게끔 -->\r\n");
      out.write("            <button disabled>");
      out.print( p );
      out.write("</button>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("          \r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(currentPage != maxPage){ 
      out.write("\r\n");
      out.write("        <button onclick=\"location.href='");
      out.print( contextPath);
      out.write("/review.bo?currentPage=");
      out.print(currentPage + 1);
      out.write("';\">&gt;</button>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      </div> \r\n");
      out.write("      <nav aria-label=\"Page navigation example\">\r\n");
      out.write("        <ul class=\"pagination justify-content-center\">\r\n");
      out.write("          <li class=\"page-item disabled\">\r\n");
      out.write("            <a class=\"page-link\">Previous</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("          <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("          <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("          <li class=\"page-item\">\r\n");
      out.write("            <a class=\"page-link\" href=\"#\">Next</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("      <button class=\"btn\">\r\n");
      out.write("        <a href=\"reviewWrite.bo\">글쓰기</a>\r\n");
      out.write("      </button>\r\n");
      out.write("      <button\r\n");
      out.write("          onclick=\"location.href='");
      out.print( contextPath);
      out.write("/renrollFrom.bo'\"\r\n");
      out.write("          type=\"button\"\r\n");
      out.write("          class=\"btn btn-outline-dark\"\r\n");
      out.write("          style=\"margin: 0 auto\"\r\n");
      out.write("          type=\"submit\"\r\n");
      out.write("                  >\r\n");
      out.write("                    글 작성\r\n");
      out.write("       </button>\r\n");
      out.write("    <!-- JavaScript Bundle with Popper -->\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
